### ISSUE TITLE
Panic occasionally with unsafe version of writeString()

### ISSUE THREAD

**Issue by zjx20** [OneOfOne/xxhash#12]
I wrote something like this in my project:
```go
    h := xxhash.New32()
    h.WriteString(param)  // please notice that |param| was passed by value, not pointer
```

And I got panic occasionally as:
```
WARN[0141] panic occurred: runtime error: invalid memory address or nil pointer dereference  func=runtime.panicmem line=62
WARN[0141] goroutine 1519 [running]:
framework/logger.GetStacktraces(0xc42052ba40, 0xc4203eebf0)
	/Users/foo/gohome/src/framework/logger/logger.go:29 +0x74
afsserver/user.catchReturnErr(0xc4203ef688)
	/Users/foo/gohome/src/afsserver/user/helpers.go:34 +0x1d9
panic(0x6215c0, 0xc4200140e0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 +0x243
github.com/OneOfOne/xxhash.writeString(0x9890a0, 0xc420493a70, 0x0, 0x0, 0x699580, 0xc4203eee01, 0xc420493a70)
	/Users/foo/gohome/src/github.com/OneOfOne/xxhash/xxhash_unsafe.go:29 +0x27
github.com/OneOfOne/xxhash.(*XXHash32).WriteString(0xc420493a70, 0x0, 0x0, 0x1, 0xc4202b4248, 0x1)
	/Users/foo/gohome/src/github.com/OneOfOne/xxhash/xxhash.go:79 +0x4b
... omitted stack
```

If I change the code to:
```go
    h := xxhash.New32()
    h.Write([]byte(param))
```
then the panic will disappeared.

**Comment by OneOfOne** [comment]
I'll look into it, is it all the time or random?

**Comment by OneOfOne** [comment]
@zjx20 I can't reproduce at all, I need more details, maybe the source of the string and the length, if you can give me a reproducible case it would be great.

**Comment by OneOfOne** [comment]
It crashes if the input is empty, I put a check for that, reopen if this commit doesn't fix your problem.

**Comment by zjx20** [comment]
Thank you for the quick reply and fix! Just curious, how fast it can gain with unsafe? Is it worth to use unsafe (since the implementation looks quite hacking) ?
